// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa2ZJF-a5Yc4XtpyBSUVV3JHA-zgrcMh4',
    appId: '1:950864470655:web:c66cc56b77f2467062954a',
    messagingSenderId: '950864470655',
    projectId: 'practice-8b219',
    authDomain: 'practice-8b219.firebaseapp.com',
    storageBucket: 'practice-8b219.firebasestorage.app',
    measurementId: 'G-CFLBGPDQCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcvGJ8B-UwBSmTXj-csEUzO3sl_Yr4nOI',
    appId: '1:950864470655:android:981cf5a2485657ad62954a',
    messagingSenderId: '950864470655',
    projectId: 'practice-8b219',
    storageBucket: 'practice-8b219.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvGN1qtIVdKZaNheDndYb_qW2Sr8pKK3c',
    appId: '1:950864470655:ios:42566acf59730bea62954a',
    messagingSenderId: '950864470655',
    projectId: 'practice-8b219',
    storageBucket: 'practice-8b219.firebasestorage.app',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvGN1qtIVdKZaNheDndYb_qW2Sr8pKK3c',
    appId: '1:950864470655:ios:42566acf59730bea62954a',
    messagingSenderId: '950864470655',
    projectId: 'practice-8b219',
    storageBucket: 'practice-8b219.firebasestorage.app',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa2ZJF-a5Yc4XtpyBSUVV3JHA-zgrcMh4',
    appId: '1:950864470655:web:27a7dbd8d4c571da62954a',
    messagingSenderId: '950864470655',
    projectId: 'practice-8b219',
    authDomain: 'practice-8b219.firebaseapp.com',
    storageBucket: 'practice-8b219.firebasestorage.app',
    measurementId: 'G-E2HGJDC71S',
  );
}
